packages/panda-preset/README.md
closes #10 
Update preset README.md links
=> chore: update README.md in preset

.vscode/settings.json, configs/package.json, configs/src/index.mjs, configs/src/publish.mjs, configs/src/versions.mjs, package.json, packages/panda-preset/package.json, pnpm-lock.yaml
closes #15 
Adds publish script to configs workspace
=> 15 feature create release channels

.github/workflows/docs-checks.yml, .github/workflows/docs-linting.yml, .github/workflows/linting.yml, .github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, configs/src/publish.mjs, package.json
closes #17 
- Adds publish-next.yml
- Adds publish-stable.yml
=> 17 feature add publish ci scripts

packages/panda-preset/src/theme/semantic-tokens/action.ts, packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/neutral.ts, packages/panda-preset/src/theme/semantic-tokens/success.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, packages/panda-preset/src/theme/semantic-tokens/warning.ts, tests/panda-preset/theme/semantic-tokens/actions.test.ts, tests/panda-preset/theme/semantic-tokens/danger.test.ts, tests/panda-preset/theme/semantic-tokens/info.test.ts, tests/panda-preset/theme/semantic-tokens/neutral.test.ts, tests/panda-preset/theme/semantic-tokens/success.test.ts, tests/panda-preset/theme/semantic-tokens/warning.test.ts
closes #20 
Updates semantic tokens to use official theme
=> 20 feature add initial semantic tokens

packages/react/src/context/theme.tsx, packages/react/src/hooks/useTheme.ts, pnpm-lock.yaml, tests/bunfig.toml, tests/happydom.ts, tests/package.json, tests/react/context/theme.test.tsx, tests/react/hooks/useTheme.test.tsx, tests/tsconfig.json, tests/utils.ts, tsconfig.json
closes #37 
Updates `tests` workspace to include react lib
=> 37 feature setup testing for react package

eslint.config.js, package.json, pnpm-lock.yaml, tests/bunfig.toml, tests/react/context/theme.test.tsx
closes #40 
- Adds react eslint plugins that have eslint v9 support
- Updates theme.test.tsx to get to 100% line coverage
=> 40 feature add jsx a11y testing

tests/react/context/theme.test.tsx
Custom implementation to render a hook
Changes to use react testing library [renderHook](https://react-hooks-testing-library.com/reference/api).
=> test: update theme test to use renderHook

docs/app/components/Admonition.tsx, docs/app/components/MatchSideNavItem.tsx, docs/app/components/Nav.tsx, docs/app/components/PageLayout.tsx, docs/app/components/SideNav.tsx, docs/app/preset/colors/colors.mdx, docs/app/preset/colors/components/ColorSwatch.tsx, docs/app/preset/colors/components/PaletteList.tsx, docs/app/preset/colors/page.tsx, docs/app/preset/layout.tsx, docs/app/preset/overview.mdx, docs/app/preset/page.tsx, docs/app/preset/side-nav.json, docs/app/preset/theme/page.tsx, docs/app/preset/theme/theme.mdx, docs/app/styles/markdown.ts
=> 47 docs add preset installation information

docs/app/components/Admonition.tsx, docs/app/components/Nav.tsx, docs/app/components/OnThisPage.tsx, docs/app/components/TypographyBlock.tsx, docs/app/preset/colors/components/ColorSwatch.tsx, docs/app/preset/layout.tsx, docs/app/preset/overview.mdx, docs/app/preset/typography/doc.mdx, docs/app/preset/typography/page.tsx, docs/app/react/layout.tsx, docs/app/react/use-theme-context/doc.mdx, docs/app/react/use-theme/doc.mdx, docs/next.config.mjs, packages/panda-preset/src/theme/semantic-tokens/action.ts, packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/success.ts, tests/panda-preset/theme/semantic-tokens/actions.test.ts, tests/panda-preset/theme/semantic-tokens/danger.test.ts, tests/panda-preset/theme/semantic-tokens/info.test.ts, tests/panda-preset/theme/semantic-tokens/success.test.ts
closes #58 
- Updates token values
- Updates ColorSwatch to be readable on both modes
- Adds high level typography page
- Adds OnThisPage component
- Updates Admonition styles
=> 58 docs general updates

.vscode/settings.json, docs/app/components/CodePreview.tsx, docs/app/components/Nav.tsx, docs/app/icons/layout.tsx, docs/app/icons/page.tsx, docs/app/icons/side-nav.json, docs/app/preset/colors/colors.mdx, docs/app/preset/colors/components/PaletteList.tsx, docs/app/preset/colors/page.tsx, docs/app/preset/layout.tsx, docs/app/preset/page.tsx, docs/app/preset/theme/page.tsx, docs/app/preset/typography/components/typography-block.tsx, docs/app/preset/typography/components/typography-list.tsx, docs/app/preset/typography/doc.mdx, docs/app/preset/typography/page.tsx, docs/app/react/layout.tsx, docs/app/react/page.tsx, docs/app/react/show/components/show-preview.tsx, docs/app/react/show/doc.mdx, docs/app/react/show/page.tsx, docs/app/react/side-nav.json, docs/app/react/use-theme-context/page.tsx, docs/app/react/use-theme/page.tsx, packages/react/src/components/Show.tsx, packages/react/src/index.ts, tests/README.md, tests/react/components/show.test.tsx
closes #60 
- Adds show component
- Adds show doc page
- Updates doc pages based on user feedback
=> 60 feature create show component

docs/app/preset/overview.mdx, docs/app/preset/theme/theme.mdx, docs/app/styles/markdown.ts
closes #66 
- Adds missing Preset installation step
- Adds inline code styles
=> 66 docs add missing preset installation step

.github/workflows/checks.yml, .github/workflows/docs-checks.yml, .github/workflows/icons-build.yml, .github/workflows/linting.yml, .github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, .prettierignore, .vscode/settings.json, CODE_OF_CONDUCT.md, CONTRIBUTING.md, docs/app/components/CodePreview.tsx, docs/app/components/SideNav.tsx, docs/app/react/button/components/button-preview.tsx, docs/app/react/button/doc.mdx, docs/app/react/button/page.tsx, docs/app/react/side-nav.json, package.json, packages/panda-preset/src/index.ts, packages/panda-preset/src/recipes/button.ts, packages/panda-preset/src/recipes/shared/button.base.ts, packages/panda-preset/src/recipes/shared/palettes.ts, packages/panda-preset/src/theme/semantic-tokens/action.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, pnpm-lock.yaml, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/shared/helpers.test.ts, tests/panda-preset/recipes/shared/palettes.test.ts, tests/panda-preset/root.test.ts, tests/panda-preset/theme/semantic-tokens/actions.test.ts
closes #75 
- Adds button recipe
- Adds Button docs page
=> 75 feature add button recipe

docs/app/preset/colors/components/ColorSwatch.tsx, docs/app/preset/conditions/doc.mdx, docs/app/preset/conditions/page.tsx, docs/app/preset/side-nav.json, docs/app/styles/markdown.ts, packages/panda-preset/src/conditions.ts, packages/panda-preset/src/globalCss.ts, tests/panda-preset/conditions.test.ts
closes #86 
- Adds new conditions
- Adds new conditions page in core section of the docs
=> 86 docs add conditions page to preset

docs/app/preset/conditions/doc.mdx, docs/app/preset/side-nav.json, docs/app/preset/utilities/doc.mdx, docs/app/preset/utilities/page.tsx
=> docs: add utilities page

docs/app/components/MatchSideNavItem.tsx, docs/app/components/Nav.tsx, docs/app/components/OnThisPage.tsx, docs/app/preset/animation/doc.mdx, docs/app/preset/patterns/components/patterns-preview.tsx, docs/app/preset/patterns/doc.mdx, docs/app/preset/patterns/page.tsx, docs/app/preset/side-nav.json, docs/app/styles/markdown.ts, docs/app/utils/const.ts
closes #90 
- Adds patterns page
- Adds focus styles
=> 90 docs add patterns page

docs/app/components/ApiLinks.tsx, docs/app/components/CodePreview.tsx, docs/app/components/MatchSideNavItem.tsx, docs/app/components/Nav.tsx, docs/app/components/PageLayout.tsx, docs/app/data/navLinks.json
closes #92 
Make the docs a little fancier
=> 92 docs high level doc updates

docs/app/components/CodePreview.tsx, docs/app/react/nav-menu/components/nav-menu-preview.tsx, docs/app/react/nav-menu/doc.mdx, docs/app/utils/const.ts, packages/panda-preset/src/theme/keyframes.ts, packages/react/src/components/NavMenuLink.tsx, packages/react/src/components/NavMenuList.tsx, tests/panda-preset/theme/keyframes.test.ts, tests/react/components/navMenuList.test.tsx
closes #102 
- Adds styling to nav menu
- Updates docs
=> 102 feature add menu styles

.github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, configs/src/publish-jsr.mjs
closes #110 
Use native pnpm `dlx`
=> ci: update publish-jsr to use dlx

configs/src/publish-jsr.mjs
closes #112 
Removes the `tag` flag from jsr publish command
=> ci: remove tag from jsr publishing

configs/src/publish-jsr.mjs
closes #114 
updates publish-jsr to use `allow-dirty`
=> ci: add allow-dirty flag

.github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, README.md, configs/src/publish-jsr.mjs, configs/src/publish.mjs, docs/app/icons/overview.mdx, docs/app/preset/overview.mdx
=> 116 bug ci playground

packages/panda-preset/src/theme/textStyles.ts
closes #100 
Updates typography descriptions
=> refactor(preset): update textStyle descriptions

docs/app/preset/overview.mdx, packages/react/src/components/Button.tsx, packages/react/src/components/IconButton.tsx, packages/react/src/components/NavMenuLink.tsx, packages/react/src/components/NavMenuList.tsx, packages/react/src/components/NavMenuTrigger.tsx, packages/react/src/global.d.ts
closes #141 
- Fixes tsup build issues by importing the .mjs files from the styled-system package
=> fix(react): use .mjs styled-system imports

configs/src/versions.mjs
=> chore: up versions.mjs

.github/workflows/publish-next.yml, .npmrc, configs/src/versions.mjs, docs/app/preset/overview.mdx, packages/react/package.json, packages/styled-system/jsr.json, packages/styled-system/panda.config.ts, pnpm-lock.yaml
closes #146 
Fixes styled-system missing module error
=> 146 bug react package failing with missing helpersmjs file

configs/src/versions.mjs
=> build: v0.1.3

docs/app/components/MatchSideNavItem.tsx, docs/app/react/label/components/label-preview.tsx, docs/app/react/label/doc.mdx, docs/app/react/label/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/label.ts, tests/panda-preset/recipes/label.test.ts
closes #127 
- Adds label recipe
- Adds Next doc page
=> 127 feature create label recipe

docs/app/react/field-message/components/field-message-preview.tsx, docs/app/react/field-message/doc.mdx, docs/app/react/field-message/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/fieldMessage.ts, packages/panda-preset/src/recipes/index.ts, packages/react/src/components/Label.tsx, tests/panda-preset/recipes/fieldMessage.test.ts, tests/react/components/label.test.tsx
closes #131 
- Adds fieldMessage recipe
- Adds doc page
=> docs(react): add Field Message page

docs/app/react/field-message/components/field-message-preview.tsx, docs/app/react/field-message/doc.mdx, packages/react/src/components/FieldMessage.tsx, packages/react/src/index.ts, pnpm-lock.yaml, tests/react/components/fieldMessage.test.tsx, tests/react/components/label.test.tsx
closes #132 
- Adds fieldMessage component
- Updates doc
=> 132 feature make fieldmessage component

configs/index.d.ts, docs/app/components/Nav.tsx, docs/app/react/field-message/components/field-message-preview.tsx, docs/app/react/input/components/input-preview.tsx, docs/app/react/input/doc.mdx, docs/app/react/input/page.tsx, docs/app/react/label/components/label-preview.tsx, docs/app/react/label/doc.mdx, docs/app/react/side-nav.json, docs/package.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/slots/input.ts, packages/react/src/components/Label.tsx, pnpm-lock.yaml, tests/bunfig.toml, tests/panda-preset/recipes/slots/input.test.ts, tests/react/components/label.test.tsx
closes #129 
- Adds input slot recipe
- Adds doc page
=> 129 feature make input recipe

.gitignore, docs/app/react/field-message/components/field-message-preview.tsx, docs/app/react/input/components/input-preview.tsx, docs/app/react/input/doc.mdx, docs/app/react/label/components/label-preview.tsx, packages/react/package.json, packages/react/src/components/Input.tsx, packages/react/src/context/field.tsx, packages/react/src/index.ts, pnpm-lock.yaml, tests/react/components/input.test.tsx
closes #130 
- Adds new Input component
- updates doc page
=> 130 feature make input component

configs/src/versions.mjs, docs/app/react/side-nav.json
=> 155 feature v020

docs/app/react/side-nav.json, docs/app/react/tabs/components/tabs-preview.tsx, docs/app/react/tabs/doc.mdx, docs/app/react/tabs/page.tsx, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx, packages/react/src/components/TabPanel.tsx, packages/react/src/context/tabs.tsx, packages/react/src/index.ts, tests/react/context/tabs.test.tsx
closes #160 
- Adds new un-styled tabs components
- Adds initial doc page
=> 160 feature make tabs components

docs/app/react/tabs/components/tabs-preview.tsx, docs/app/react/tabs/doc.mdx, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx, packages/react/src/components/TabPanel.tsx, tests/react/context/tabs.test.tsx
closes #159 
Adds styling to tabs components
=> 159 feature make tabs recipe

.vscode/settings.json, docs/app/react/tabs/components/tabs-preview.tsx, docs/app/react/tabs/doc.mdx, packages/react/src/aria-helpers/tabs.aria.ts, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx, packages/react/src/components/TabPanel.tsx, packages/react/src/context/tabs.tsx, packages/react/src/index.ts, tests/bunfig.toml, tests/react/aria-helpers/tabsAria.test.tsx, tests/react/context/tabs.test.tsx
closes #163 
- Enhances Tabs component API
- Adds keyboard navigation to Tabs
=> 163 feature add keyboard navigation to tabs family

.vscode/settings.json, configs/src/versions.mjs, docs/app/components/CodePreview.tsx, docs/app/components/FeatureHeader.tsx, docs/app/components/OverviewList.tsx, docs/app/components/PageTabs.tsx, docs/app/react/field-message/doc.mdx, docs/app/react/tabs/a11y.mdx, docs/app/react/tabs/dev.mdx, docs/app/react/tabs/guidelines.mdx, docs/app/react/tabs/overview.mdx, docs/app/react/tabs/page.tsx, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx
closes #161 
- Adds new Tabbed page content for the Tabs component
=> docs: save tabs state

configs/src/versions.mjs, docs/app/components/PageTabs.tsx, docs/app/react/tabs/components/tabs-preview.tsx, docs/app/react/tabs/dev.mdx, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx, packages/react/src/context/tabs.tsx, tests/react/context/tabs.test.tsx
closes #170 
- Update tabs context to use and set initial cached tab
- Add support for multiple tabs on a single page with caching
=> 170 bug cached tabs does clears state before UI renders

docs/app/react/button/a11y.mdx, docs/app/react/button/dev.mdx, docs/app/react/button/guidelines.mdx, docs/app/react/button/overview.mdx, docs/app/react/button/page.tsx, docs/app/react/tabs/a11y.mdx, docs/app/react/tabs/components/tabs-preview.tsx, docs/app/react/tabs/guidelines.mdx, docs/app/react/tabs/overview.mdx
closes #172 
- Updates button page to include new content
=> 172 docs use pagetabs in button page 1

docs/app/components/OverviewList.tsx, docs/app/react/button/page.tsx, docs/app/react/icon-button/a11y.mdx, docs/app/react/icon-button/dev.mdx, docs/app/react/icon-button/guidelines.mdx, docs/app/react/icon-button/overview.mdx, docs/app/react/icon-button/page.tsx, docs/app/styles/markdown.ts, docs/app/utils/const.ts, docs/mdx-components.tsx
closes #173 
- Updates icon button page to use PageTabs
- Makes MDX table fancier
=> docs: update icon-button page to use PageTabs

docs/app/page.tsx, docs/app/react/label/a11y.mdx, docs/app/react/label/components/label-preview.tsx, docs/app/react/label/dev.mdx, docs/app/react/label/guidelines.mdx, docs/app/react/label/overview.mdx, docs/app/react/label/page.tsx
closes #176 
- Updates Label page to use PageTabs
=> docs: use PageTabs for Label

docs/app/react/field-message/a11y.mdx, docs/app/react/field-message/dev.mdx, docs/app/react/field-message/guidelines.mdx, docs/app/react/field-message/overview.mdx, docs/app/react/field-message/page.tsx, docs/app/react/input/a11y.mdx, docs/app/react/input/overview.mdx
closes #174 
Updates Field Message to use page tabs
=> docs: update Field Message to use PageTabs

docs/app/components/FeatureHeader.tsx, docs/app/components/OnThisPage.tsx, docs/app/components/PageLayout.tsx, docs/app/components/PageTabs.tsx, docs/app/react/button/dev.mdx, docs/app/react/button/overview.mdx, docs/app/react/button/page.tsx, docs/app/react/field-message/dev.mdx, docs/app/react/field-message/overview.mdx, docs/app/react/field-message/page.tsx, docs/app/react/icon-button/dev.mdx, docs/app/react/icon-button/overview.mdx, docs/app/react/icon-button/page.tsx, docs/app/react/input/dev.mdx, docs/app/react/input/overview.mdx, docs/app/react/input/page.tsx, docs/app/react/label/dev.mdx, docs/app/react/label/overview.mdx, docs/app/react/label/page.tsx, docs/app/react/nav-menu/dev.mdx, docs/app/react/nav-menu/overview.mdx, docs/app/react/nav-menu/page.tsx, docs/app/react/tabs/dev.mdx, docs/app/react/tabs/overview.mdx, docs/app/react/tabs/page.tsx
closes #186 
Updates all tab-based pages to use a new layout that gets the on this page links working with each tab panel
=> 186 docs create specific layout for tabbed paged

.vscode/settings.json, docs/app/react/side-nav.json, docs/app/react/textarea/a11y.mdx, docs/app/react/textarea/components/textarea-preview.tsx, docs/app/react/textarea/dev.mdx, docs/app/react/textarea/guidelines.mdx, docs/app/react/textarea/overview.mdx, docs/app/react/textarea/page.tsx, packages/react/src/components/Textarea.tsx, packages/react/src/index.ts, tests/react/components/textarea.test.tsx
closes #190 #191 
Adds Textarea component
=> 191 feature make textarea component

docs/app/react/side-nav.json, docs/app/react/tooltip/a11y.mdx, docs/app/react/tooltip/components/tooltip-preview.tsx, docs/app/react/tooltip/dev.mdx, docs/app/react/tooltip/guidelines.mdx, docs/app/react/tooltip/overview.mdx, docs/app/react/tooltip/page.tsx, packages/panda-preset/src/conditions.ts, packages/panda-preset/src/globalCss.ts, packages/react/src/components/IconButton.tsx, tests/panda-preset/conditions.test.ts
closes #193 
Adds new Tooltip API and Docs page
=> 193 feature make tooltip api

docs/app/react/tooltip/components/tooltip-preview.tsx, docs/app/react/tooltip/dev.mdx, docs/app/react/tooltip/overview.mdx, packages/panda-preset/src/globalCss.ts
closes #195 
Fine tunes tooltip styling
=> feat: update tooltip exact positioning

docs/app/react/side-nav.json, docs/app/react/tags/components/closable-tag-preview.tsx, docs/app/react/tags/components/tag-preview.tsx, docs/app/react/tags/dev.mdx, docs/app/react/tags/guidelines.mdx, docs/app/react/tags/overview.mdx, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/shared/tag.base.ts, packages/panda-preset/src/recipes/tag.ts, packages/react/src/components/Tag.tsx, pnpm-lock.yaml, tests/panda-preset/recipes/tag.test.ts, tests/react/components/tag.test.tsx
closes #198 
- Adds tag recipe to component
- Updates docs
=> 198 feature make tags recipe

packages/react/src/components/Tag.tsx, pnpm-lock.yaml, tests/react/components/tag.test.tsx
closes #202 
Updates Tag to use recipe
=> chore: add tag recipe to component

docs/app/preset/colors/components/ColorSwatch.tsx, docs/app/preset/colors/components/PaletteList.tsx, packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/neutral.ts, packages/panda-preset/src/theme/semantic-tokens/success.ts, packages/panda-preset/src/theme/semantic-tokens/warning.ts, tests/panda-preset/theme/semantic-tokens/info.test.ts, tests/panda-preset/theme/semantic-tokens/success.test.ts, tests/panda-preset/theme/semantic-tokens/warning.test.ts
closes #205 
Updates state tokens to include a `bg` for consistency
=> feat: add bg tokens to info, success, warning

.vscode/settings.json, docs/app/preset/utilities/doc.mdx, packages/panda-preset/src/utilities.ts, tests/panda-preset/utilities.test.ts
closes #203 
- Adds `cerbGradient` or `cerberusGradient` to utilities
- Updates doc page
=> 203 feature add cerberusgradient to utilities

docs/app/react/tags/components/tag-preview.tsx, docs/app/react/tags/dev.mdx, packages/panda-preset/src/utilities.ts, tests/panda-preset/utilities.test.ts
closes #208 
- Fine tunes `cerbGradient` utility
- Adds utility to Tag custom option
=> feat(preset): update cerbGradient

docs/app/react/icon-button/components/icon-button-preview.tsx, docs/app/react/icon-button/dev.mdx, packages/panda-preset/src/recipes/iconButton.ts, packages/react/src/components/IconButton.tsx, packages/react/src/components/Tag.tsx, tests/panda-preset/recipes/iconButton.test.ts, tests/react/components/iconButton.test.tsx
closes #210 
Adds sizing to icon button
=> 210 feature add all palette and sizes to icon button

packages/react/src/components/IconButton.tsx, packages/react/src/components/Tag.tsx, pnpm-lock.yaml, tests/react/components/iconButton.test.tsx
closes #212 
Updates Tag to use IconButton sm size
=> feat(react): update Tag to use sm IconButton

docs/app/react/tooltip/components/tooltip-preview.tsx, docs/app/react/tooltip/dev.mdx, packages/panda-preset/src/globalCss.ts
closes #215 
Updates the tooltip styles to include arrows (even though it's obvious that the information bubble appearing is coming from the thing you are hovering over... 👀 )
=> feat(preset): add arrows to tooltip

configs/src/versions.mjs, docs/app/react/side-nav.json
=> 214 feature v040

.github/workflows/publish-figma.yml, .gitignore, eslint.config.js, figma/figma.config.json, figma/package.json, figma/src/button.figma.tsx, figma/src/icons/arrow-left-icon.tsx, figma/src/icons/arrow-right-icon.tsx, figma/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
closes #219 
Adds Figma workspace
=> 219 feature setup figma code connect

.github/workflows/sync-figma.yml, figma/package.json, figma/scripts/create-icon-sets.ts, figma/scripts/variables/color.ts, figma/scripts/variables/figma-api.ts, figma/scripts/variables/figma.types.ts, figma/scripts/variables/sync-figma.ts, figma/scripts/variables/token-export.ts, figma/scripts/variables/utils.ts, packages/panda-preset/src/tokens/primitives-colors.cerberus.json, packages/panda-preset/src/tokens/primitve-typography.value.json, packages/panda-preset/src/tokens/semantic-colors.dark-mode.json, packages/panda-preset/src/tokens/semantic-colors.light-mode.json, packages/panda-preset/src/tokens/spacing.mode-1.json, packages/panda-preset/src/tokens/text-styles.desktop.json, packages/panda-preset/src/tokens/text-styles.mobile.json, pnpm-lock.yaml
closes #221 
- Adds Figma sync script
- Adds initial figma token files
- Adds Figma sync CI job
=> 221 feature convert figma icons to sets

.github/workflows/sync-figma.yml
closes #225 
Adds the `allow-empty` flag so lint-staged doesn't block GH from creating a PR
=> ci: update sync-figma.yml

.github/workflows/sync-figma.yml, .husky/pre-commit
closes #227 
Adds `allow-empty` flag to husky pre-commit to prevent figma sync PR blocking
=> ci: update husky to use --allow-empty

configs/src/versions.mjs, docs/app/preset/side-nav.json, docs/app/react/side-nav.json
=> 233 feature v050 tokens update

configs/src/versions.mjs, packages/panda-preset/src/tokens/index.ts
closes #236 
Adds assert import for JSON files and JSR
=> chore: add JSON assert for JSR

configs/src/versions.mjs, packages/panda-preset/src/tokens/index.ts
=> chore: 0.5.2 - JSR with

docs/app/components/Admonition.tsx, docs/app/react/button/components/button-preview.tsx, docs/app/react/button/dev.mdx, docs/app/react/button/overview.mdx, docs/app/react/icon-button/components/icon-button-preview.tsx, docs/app/react/icon-button/dev.mdx, docs/app/react/icon-button/guidelines.mdx, docs/app/react/icon-button/overview.mdx, figma/src/button.figma.tsx, figma/src/icons/arrow-left-icon.figma.tsx, figma/src/icons/arrow-right-icon.figma.tsx, packages/panda-preset/src/recipes/button.ts, packages/panda-preset/src/recipes/iconButton.ts, packages/panda-preset/src/recipes/shared/button.base.ts, packages/react/package.json, packages/react/src/components/Button.tsx, packages/react/src/components/IconButton.tsx, packages/react/tsconfig.json, packages/react/tsup.config.ts, pnpm-lock.yaml, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/iconButton.test.ts, tests/react/components/NavMenuTrigger.test.tsx, tests/react/components/button.test.tsx, tests/react/components/tag.test.tsx
closes #242 
Makes button recipe usage options more consistent
=> refactor(preset): update button recipe to use outlined over outline

figma/figma.config.json, figma/package.json, figma/src/iconButton.figma.tsx, pnpm-lock.yaml
closes #253 
Updates Code Connect to support IconButtons
=> feat(figma): add IconButton CC

figma/package.json, figma/scripts/create-icons.ts, figma/src/icons/close-icon.figma.tsx, figma/tsconfig.json
closes #256 
Adds Close icon to Code Connect
=> 256 feature test dynamically creating icon figma files

figma/figma.config.json, figma/package.json, figma/scripts/create-icons.ts, figma/src/fieldMessage.figma.tsx, figma/src/icons/add-icon.figma.tsx, figma/src/icons/arrow-down-icon.figma.tsx, figma/src/icons/information-filled-icon.figma.tsx, figma/src/icons/information-icon.figma.tsx, figma/src/input.figma.tsx, figma/src/label.figma.tsx, figma/src/tag.figma.tsx, figma/src/tooltip.figma.tsx, figma/tsconfig.json
closes #259 
Input, label, fieldmessage not working but working with Figma team to figure out the issue
=> 259 feature input code connect to figma

docs/app/react/tags/components/closable-tag-preview.tsx, docs/app/react/tags/components/tag-preview.tsx, docs/app/react/tags/dev.mdx, figma/src/tag.figma.tsx, packages/panda-preset/src/recipes/tag.ts, packages/react/src/components/Button.tsx, packages/react/src/components/IconButton.tsx, packages/react/src/components/Tag.tsx, tests/panda-preset/recipes/tag.test.ts, tests/react/components/tag.test.tsx
closes #262 
Updates Button, IconButton, Tag to use RecipeVariantProps
=> 262 feature add consistent types in react

figma/src/textarea.figma.tsx
closes #261 
Adds Textarea CC connect
=> feat(figma): add Textarea CC

docs/app/react/input/components/input-preview.tsx, docs/app/react/input/dev.mdx, docs/app/react/input/overview.mdx, docs/app/react/side-nav.json, figma/src/input.figma.tsx, packages/panda-preset/src/recipes/slots/input.ts, packages/react/src/components/Input.tsx, pnpm-lock.yaml, tests/package.json, tests/panda-preset/recipes/slots/input.test.ts, tests/react/components/input.test.tsx
closes #278 
Updates Input component to accept `startIcon` and `endIcon` props
=> 278 feature update icon to support starticon

docs/app/react/radio/a11y.mdx, docs/app/react/radio/components/input-preview.tsx, docs/app/react/radio/components/radio-preview.tsx, docs/app/react/radio/dev.mdx, docs/app/react/radio/guidelines.mdx, docs/app/react/radio/overview.mdx, docs/app/react/radio/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/shared/input.base.ts, packages/panda-preset/src/recipes/slots/input.ts, packages/panda-preset/src/recipes/slots/radio.ts, tests/panda-preset/recipes/slots/radio.test.ts
closes #282 
- add radio recipe
- adds new Radio page in React section
=> 282 feature make radio recipe

.vscode/settings.json, docs/app/layout.tsx, docs/app/react/installation.mdx, docs/app/react/layout.tsx, docs/app/react/side-nav.json, docs/app/react/toggle/components/toggle-preview.tsx, docs/app/react/toggle/dev.mdx, docs/app/react/use-toggle/doc.mdx, docs/app/react/use-toggle/page.tsx, docs/app/shared-metadata.ts, figma/src/toggle.figma.tsx, packages/panda-preset/src/recipes/fieldMessage.ts, packages/panda-preset/src/recipes/slots/toggle.ts, packages/react/src/components/Toggle.tsx, packages/react/src/config/cerbIcons.ts, packages/react/src/hooks/useToggle.ts, packages/react/src/index.ts, tests/panda-preset/recipes/fieldMessage.test.ts, tests/react/components/toggle.test.tsx, tests/react/helpers/config.test.ts, tests/react/hooks/useToggle.test.tsx
closes #291 
- Adds Toggle and useToggle to React API
- Update docs
- Adds Figma support
=> 291 feature make toggle component

configs/src/versions.mjs, docs/app/preset/side-nav.json, docs/app/react/radio/dev.mdx, docs/app/react/side-nav.json
=> chore: v0.6.0

docs/app/preset/theme/theme.mdx
closes #230 
Updates theme.mdx to be a little more visual and have better information
=> docs: update theme.mdx

docs/app/components/CategoryList.tsx, docs/app/components/PageTabs.tsx, docs/app/data/categories.json, docs/app/react/dev.mdx, docs/app/react/overview.mdx, docs/app/react/page.tsx, docs/app/react/side-nav.json
closes #311 
Updates React home page to be designer/dev friendly
=> docs: add getting started page for react

docs/app/components/CategoryList.tsx, docs/app/preset/colors/[name]/components/color-details.tsx, docs/app/preset/colors/[name]/components/usage-example.tsx
closes #314 
- Shows correct color and details based on mode set on site
- Adds super high level usage example
=> chore: Add lazy loading for images and update color details component

docs/app/components/CategoryList.tsx, docs/app/components/FeatureHeader.tsx, docs/app/components/PaletteSwatch.tsx, docs/app/preset/theme/theme.mdx, docs/app/react/overview.mdx, docs/app/utils/const.ts
=> 318 docs components home page updates

docs/app/components/PaletteSwatch.tsx, docs/app/preset/side-nav.json, docs/app/preset/theme/theme.mdx, packages/panda-preset/src/index.ts, packages/panda-preset/src/recipes/shared/palettes.ts, packages/panda-preset/src/theme/semantic-tokens/index.ts, packages/panda-preset/src/theme/semantic-tokens/secondary-action.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, packages/panda-preset/src/tokens/index.ts, tests/panda-preset/recipes/shared/helpers.test.ts, tests/panda-preset/theme/semantic-tokens/secondary-action.test.ts
closes #308 
- Adds secondaryAction palette
- Updates docs theme to promote it
=> 308 feature add secondary action palette

docs/app/preset/colors/[name]/components/color-details.tsx, docs/app/preset/colors/[name]/components/usage-example.tsx, packages/panda-preset/src/index.ts
=> docs: update usage to include secondary color

docs/app/preset/colors/[name]/components/color-details.tsx, packages/panda-preset/src/recipes/shared/button.base.ts, packages/panda-preset/src/theme/semantic-tokens/action.ts, packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/secondary-action.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, packages/panda-preset/src/tokens/semantic-colors.dark-mode.json, packages/panda-preset/src/tokens/semantic-colors.light-mode.json, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/iconButton.test.ts, tests/panda-preset/theme/semantic-tokens/action.test.ts, tests/panda-preset/theme/semantic-tokens/danger.test.ts, tests/panda-preset/theme/semantic-tokens/secondary-action.test.ts
closes #329 
- Kills deprecated tokens
- Adds ghost usage
- updates buttons to use ghost usage
=> feat: add ghost tokens

docs/app/react/feature-flags/components/feature-flags-preview.tsx, docs/app/react/feature-flags/doc.mdx, docs/app/react/feature-flags/page.tsx, docs/app/react/side-nav.json, packages/react/src/components/FeatureFlag.tsx, packages/react/src/context/feature-flags.tsx, packages/react/src/index.ts, tests/react/context/feature-flags.test.tsx
closes #340 
Adds Feature Flags Provider and component
=> 340 feature create featureflagprovider component

docs/app/data/categories.json, docs/app/react/prompt-modal/a11y.mdx, docs/app/react/prompt-modal/components/confirm-modal-features.tsx, docs/app/react/prompt-modal/components/confirm-modal-preview.tsx, docs/app/react/prompt-modal/components/prompt-modal-features.tsx, docs/app/react/prompt-modal/components/prompt-modal-preview.tsx, docs/app/react/prompt-modal/dev.mdx, docs/app/react/prompt-modal/guidelines.mdx, docs/app/react/prompt-modal/overview.mdx, docs/app/react/prompt-modal/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/label.ts, packages/panda-preset/src/recipes/shared/input.base.ts, packages/panda-preset/src/recipes/slots/confirm-modal.ts, packages/react/src/context/confirm-modal.tsx, packages/react/src/context/prompt-modal.tsx, packages/react/src/index.ts, tests/panda-preset/recipes/label.test.ts, tests/panda-preset/recipes/slots/input.test.ts, tests/react/context/prompt-modal.test.tsx
closes #346 
- Adds Prompt modal API
- Adds docs
=> 346 feature make promptmodal api

packages/react/src/config/cerbIcons.ts, packages/react/src/context/prompt-modal.tsx, tests/react/helpers/config.test.ts
closes #349 
Adds `promptModal` to defineIcons list
=> feat: add promptModal to defineIcons

docs/app/preset/animation/components/animate-in-down-preview.tsx, docs/app/preset/animation/doc.mdx, docs/app/preset/side-nav.json
=> docs: add fadeInDown animation

configs/src/versions.mjs, docs/app/preset/side-nav.json, docs/app/react/side-nav.json, packages/panda-preset/src/tokens/index.ts
=> 361 feature v070

configs/src/versions.mjs, packages/react/package.json, pnpm-lock.yaml
closes #365 
Kills the workspace version specifier to prevent npm console install errors
=> chore: kill workspace version specifier in package.json

configs/src/versions.mjs
=> chore: Bump version to 0.7.2

configs/src/versions.mjs, docs/app/preset/overview.mdx, packages/react/package.json
=> 377 feature v073 update react types path

.github/workflows/publish-next.yml, configs/src/publish.mjs, docs/app/preset/overview.mdx
npm is failing to publish
Fixes it
=> chore: temp update publish-next.yml

.github/ISSUE_TEMPLATE/feature.yml, docs/app/components/MatchSideNavItem.tsx, docs/app/components/SideNav.tsx, docs/app/data/categories.json, docs/app/preset/side-nav.json, docs/app/react/notification/components/messages.data.json, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/slots/notification.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/warning.ts, packages/panda-preset/src/tokens/semantic-colors.dark-mode.json, packages/panda-preset/src/tokens/semantic-colors.light-mode.json, packages/react/src/components/Notification.tsx, packages/react/src/context/notification-center.tsx, tests/panda-preset/recipes/slots/notification.test.ts, tests/panda-preset/theme/semantic-tokens/info.test.ts, tests/panda-preset/theme/semantic-tokens/warning.test.ts
closes #397 
- Touch up notification styles
- Adds "Close all" button
- Re-organizes Components side nav
=> 397 notification touch up

.vscode/extensions.json
closes #400 
Adds recommended extensions to vscode dir
=> chore: add recommended extensions

configs/src/versions.mjs, docs/app/preset/side-nav.json, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/shared/input.base.ts, tests/panda-preset/recipes/slots/input.test.ts
=> 414 feat v080

docs/app/layout.tsx, docs/app/shared-metadata.ts, docs/package.json, pnpm-lock.yaml
closes #423 
- Updates next to latest version
- Adds more meta info
=> chore: up next & metadata info

docs/app/react/icon-button/components/live-preview.tsx, docs/app/react/icon-button/dev.mdx, docs/app/react/icon-button/overview.mdx, packages/panda-preset/src/globalCss.ts
closes #429 
Updates IconButton to use live-playground
=> chore: Add live preview to icon button documentation

docs/app/data/categories.json, docs/app/react/select/a11y.mdx, docs/app/react/select/components/input-preview.tsx, docs/app/react/select/components/select-preview.tsx, docs/app/react/select/dev.mdx, docs/app/react/select/guidelines.mdx, docs/app/react/select/overview.mdx, docs/app/react/select/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/shared/input.base.ts, packages/panda-preset/src/recipes/slots/select.ts, tests/panda-preset/recipes/slots/input.test.ts, tests/panda-preset/recipes/slots/select.test.ts
closes #433 
- Adds new select slot recipe
- Adds Select docs section (WIP)
=> 433 feat make select recipe

docs/app/data/categories.json, docs/app/react/checkbox/a11y.mdx, docs/app/react/checkbox/components/checkbox-preview.tsx, docs/app/react/checkbox/components/radio-preview.tsx, docs/app/react/checkbox/dev.mdx, docs/app/react/checkbox/guidelines.mdx, docs/app/react/checkbox/overview.mdx, docs/app/react/checkbox/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/label.ts, packages/panda-preset/src/recipes/slots/checkbox.ts, packages/panda-preset/src/recipes/slots/radio.ts, tests/panda-preset/recipes/label.test.ts, tests/panda-preset/recipes/slots/checkbox.test.ts
closes #448 
- Adds checkbox recipe
- Adds Checkbox docs
=> 448 feat make checkbox recipe

docs/app/components/code-builder/builder-layout.tsx, docs/app/components/code-builder/builder-snippet.tsx, docs/app/react/button/components/live-playground.tsx
closes #447 
Adds copy/paste button to live code snippets
=> docs: add copy/paste button to live previews

configs/src/tsup.mjs, configs/src/versions.mjs, packages/react/package.json
closes #468 
Adds CJS support in React build 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮 🤮
=> feat(react): support cjs 🤮

packages/panda-preset/src/theme/semantic-tokens/action.ts, packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/page.ts, packages/panda-preset/src/theme/semantic-tokens/secondary-action.ts, packages/panda-preset/src/theme/semantic-tokens/success.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, packages/panda-preset/src/theme/semantic-tokens/warning.ts, tests/panda-preset/theme/semantic-tokens/action.test.ts, tests/panda-preset/theme/semantic-tokens/danger.test.ts, tests/panda-preset/theme/semantic-tokens/info.test.ts, tests/panda-preset/theme/semantic-tokens/secondary-action.test.ts, tests/panda-preset/theme/semantic-tokens/success.test.ts, tests/panda-preset/theme/semantic-tokens/warning.test.ts
closes #478 
Adds static tokens to all non-page palettes
=> feat(preset): add static tokens

docs/app/components/CategoryList.tsx, docs/app/components/FeatureHeader.tsx, docs/app/components/MatchFeatureImg.tsx, docs/app/components/feature-art/misc.tsx, docs/app/react/loading-states/a11y.mdx, docs/app/react/loading-states/components/loading-preview.tsx, docs/app/react/loading-states/dev.mdx, docs/app/react/loading-states/guidelines.mdx, docs/app/react/loading-states/overview.mdx, docs/app/react/loading-states/page.tsx, docs/app/react/side-nav.json, packages/panda-preset/src/globalCss.ts
closes #483 
closes #484 
Adds new Skeletor API
=> 483 feat make skeleton recipe

docs/app/react/button/components/button-preview.tsx, docs/app/react/button/components/live-playground.tsx, docs/app/react/button/dev.mdx, docs/app/react/button/guidelines.mdx, docs/app/react/button/overview.mdx, docs/app/react/icon-button/components/icon-button-preview.tsx, docs/app/react/icon-button/components/live-preview.tsx, docs/app/react/icon-button/dev.mdx, docs/app/react/icon-button/guidelines.mdx, docs/app/react/icon-button/overview.mdx, docs/app/react/loading-states/components/loading-preview.tsx, packages/panda-preset/src/recipes/button.ts, packages/panda-preset/src/recipes/iconButton.ts
closes #485 
Updates button APIs to support 👻
=> 485 feat buttons iconbuttons should support ghost usage

configs/src/versions.mjs, docs/app/icons/overview.mdx
=> chore: v0.9.0

docs/app/react/avatar/components/live-playground.tsx, packages/panda-preset/src/recipes/avatar.ts, tests/panda-preset/recipes/avatar.test.ts
closes #507 
Updates avatar recipe to support `none` gradient variant
=> feat(react): add none option to gradients in avatar

configs/src/versions.mjs
=> chore: v0.9.2

docs/app/components/Nav.tsx, docs/app/components/page-hero.tsx, docs/app/components/squiggly-divider.tsx, docs/app/preset/customizing/components/hero.tsx, docs/app/preset/customizing/doc.mdx, docs/app/preset/customizing/page.tsx, docs/app/preset/side-nav.json, packages/panda-preset/src/tokens/index.ts, packages/react/src/hooks/useTheme.ts
closes #536 
closes #530 
- Support "system" color mode in docs
- Add customization page
=> 536 feat support system color mode

configs/src/versions.mjs, packages/panda-preset/src/theme-contract.ts
closes #573 
Adds missing strict typing to defineTheme helper
=> 573 bug jsr build updates

configs/src/versions.mjs, packages/react/src/components/Portal.tsx
closes #577 
Updates the Portal to be a client component
=> 577 bug portal should use client

configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json, docs/app/react/icon-button/dev.mdx, docs/app/react/portal/components/portal-preview.tsx, docs/app/react/side-nav.ts, docs/app/react/tooltip/components/tooltip-preview.tsx, packages/react/src/components/CircularProgress.tsx, packages/react/src/components/IconButton.tsx, packages/react/src/components/Portal.tsx, tests/react/components/iconButton.test.tsx, tests/react/components/portal.test.tsx
closes #580 
- fine tune CircularProgress styles
- removes tooltip from IconButton
- updates Portal to be Next15 compatible
=> 580 feat circularprogress style fine tuning

docs/app/components/Nav.tsx, docs/app/components/home-hero.tsx
closes #594 
Adds badges and logo to home page
=> docs: spice up home page a smidge

docs/app/components/Nav.tsx, docs/app/layout.tsx, docs/app/page.tsx, docs/app/preset/z-index/components/z-preview.tsx, docs/app/react/page.tsx, docs/app/react/tabs/components/tabs-preview.tsx, packages/react/src/components/Tab.tsx, packages/react/src/components/TabList.tsx, packages/react/src/components/TabPanel.tsx, tests/react/context/tabs.test.tsx
closes #606 
- Updates docs - home & core routes to pass
- Add missing `role` to tablist
=> 606 feat docs react aria audit

docs/app/react/page.tsx
closes #611 
Hotfix for broken react content middle section
=> hotfix: fix React main page

.github/workflows/checks.yml, .github/workflows/icons-build.yml, .github/workflows/linting.yml, .github/workflows/publish-figma.yml, .github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, .github/workflows/sync-figma.yml, docs/app/components/drip-divider.tsx, docs/app/components/hero.tsx, docs/app/layout.tsx, docs/app/preset/customizing/doc.mdx, docs/app/preset/side-nav.json, docs/app/preset/spacing/components/spacing-visual.tsx, docs/app/preset/spacing/doc.mdx, docs/app/preset/spacing/page.tsx, docs/app/react/fieldset/guidelines.mdx, docs/app/react/fieldset/overview.mdx, docs/app/react/loading-states/guidelines.mdx, docs/app/react/loading-states/overview.mdx, docs/app/react/progress-indicators/overview.mdx, package.json, packages/panda-preset/src/theme-contract.ts, packages/panda-preset/src/theme/tokens.ts, packages/panda-preset/src/tokens/index.ts, packages/react/src/components/ModalHeader.tsx, packages/react/src/components/Radio.tsx, packages/react/src/context/prompt-modal.tsx
closes #639 
Adds spacing tokens to the preset
=> 639 feat spacing tokens

packages/panda-preset/src/recipes/shared/button.base.ts, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/iconButton.test.ts, tests/panda-preset/recipes/slots/notification.test.ts
closes #642 
Updates buttons to use pointer cusor
=> feat: update button to use pointer cursor

configs/src/versions.mjs, packages/react/src/components/Admonition.tsx, packages/react/src/components/Legend.tsx
closes #662 
Kills bad import paths that snuck through in new components
=> fix(react): remove bad cerb import paths

docs/app/preset/side-nav.json, docs/app/preset/utilities/doc.mdx
closes #665 
Updates table to include borderGradient
=> docs: add utilities tag

docs/app/react/tag/components/closable-tag-preview.tsx, docs/app/react/tag/components/live-playground.tsx, docs/app/react/tag/components/match-gradient-tag.tsx, docs/app/react/tag/dev.mdx, docs/app/react/tag/guidelines.mdx, docs/app/react/tag/overview.mdx, packages/react/src/components/Tag.tsx, tests/react/components/tag.test.tsx
closes #521 
Updates Tag page to use live playground
=> docs: add Tag live playground

docs/mdx-components.tsx
closes #678 
Adds my to mdx headings
=> docs: let the headings breathe

docs/app/components/Nav.tsx, docs/app/components/home-hero-text.tsx, docs/app/components/home-hero.tsx, docs/app/data/categories.react.json, docs/app/page.tsx, docs/app/react/cta-modal/a11y.mdx, docs/app/react/cta-modal/components/cta-modal-features.tsx, docs/app/react/cta-modal/components/cta-modal-preview.tsx, docs/app/react/cta-modal/dev.mdx, docs/app/react/cta-modal/guidelines.mdx, docs/app/react/cta-modal/overview.mdx, docs/app/react/cta-modal/page.tsx, packages/react/src/components/ModalHeader.tsx, packages/react/src/components/Notification.tsx, packages/react/src/config/cerbIcons.ts, packages/react/src/context/cta-modal.tsx, packages/react/src/index.ts, tests/react/context/cta-modal.test.tsx
closes #677 
Adds new CTA Modal
=> 677 feat make cta model api

docs/app/react/menu/components/menu-preview.tsx, docs/app/react/menu/dev.mdx, packages/panda-preset/src/recipes/slots/menu.ts, packages/panda-preset/src/theme/index.ts, packages/panda-preset/src/theme/keyframes.ts, packages/panda-preset/src/theme/motionStyles.ts, packages/panda-preset/src/types.ts, tests/panda-preset/recipes/slots/menu.test.ts, tests/panda-preset/theme/keyframes.test.ts
closes #695 
- Adds a ton of new keyframes
- Proactively adds `motionStyles` for when new API ships
=> 695 feat keyframe animation tokens

docs/app/react/forms/components/standard-layout.tsx, docs/app/react/forms/dev.mdx, docs/app/react/forms/overview.mdx, docs/app/react/forms/page.tsx, docs/app/react/select/components/live-preview.tsx, docs/app/react/side-nav.ts, docs/app/react/tooltip/components/tooltip-preview.tsx, packages/panda-preset/src/globalCss.ts
closes #701 
- Adds new form section for peoples making forms
- Adds missing type imports in Select live playground
=> 701 docs docs guidelines examples

docs/app/components/CodePreview.tsx, docs/app/preset/colors/components/usage-example.tsx, docs/app/react/input/components/date-input.tsx, docs/app/react/input/components/input-preview.tsx, docs/app/react/input/overview.mdx, docs/app/react/modal/components/lazy-modal-trigger.tsx, docs/app/react/side-nav.ts, docs/app/react/use-date/doc.mdx, docs/app/react/use-date/page.tsx, docs/app/react/use-modal/doc.mdx, figma/src/button.figma.tsx, figma/src/iconButton.figma.tsx, packages/panda-preset/src/recipes/button.ts, packages/panda-preset/src/recipes/iconButton.ts, packages/react/src/context/notification-center.tsx, packages/react/src/hooks/useDate.ts, packages/react/src/index.ts, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/iconButton.test.ts, tests/react/components/NavMenuTrigger.test.tsx, tests/react/components/button.test.tsx, tests/react/components/iconButton.test.tsx, tests/react/hooks/useDate.test.tsx
closes #721 
Exposes a useDate hook and some date related helpers
=> 721 feat create usemilitarydate hook

configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json, docs/app/react/side-nav.ts
=> chore: bump version 0.13.0

configs/src/versions.mjs
=> chore: 0.13.1

docs/app/react/side-nav.ts, docs/app/react/use-root-colors/components/canvas-preview.tsx, docs/app/react/use-root-colors/doc.mdx, docs/app/react/use-root-colors/page.tsx, docs/app/scene.tsx, packages/react/src/hooks/useRootColors.ts, packages/react/src/index.ts, tests/react/hooks/useRootColors.test.tsx
closes #734 
Adds new hook for accessing Cerberus colors to use within a `canvas` element
=> 734 feat create usecanvascolors hook

packages/react/src/components/Portal.tsx
closes #742 
Updates Cerb to use the ark-ui portal for better a11y and SSR support
=> fix: use Ark portal

docs/app/components/CategoryList.tsx, docs/app/components/ui/category-card.tsx
=> docs: make component cards fancy

packages/react/src/components/DatePicker.client.tsx
closes #793 
Temporarily comments out buggy ark code for DP formatting
=> fix(react): remove ark datepicker format bug

configs/src/versions.mjs, packages/panda-preset/src/patterns.ts
closes #809 
Updates preset/patterns to use strict JSR export rules
=> chore: update patterns to use strict JSR rules

configs/src/versions.mjs, packages/react/README.md, packages/react/package.json, packages/react/src/components/Accordion.tsx, packages/react/src/components/Text.tsx, packages/react/src/config/cerbIcons.ts, packages/react/tsconfig.json, pnpm-lock.yaml, tsconfig.base.json
closes #812 
Removes workspace path from React file
=> fix: update Text.tsx to use correct path

docs/app/react/accordion/components/live-playground.tsx, docs/app/react/accordion/dev.mdx
closes #815 
Makes the Accordion dev docs a little easier to understand
=> docs: update accordion page

configs/src/versions.mjs
=> chore: remove icons from versions.mjs

docs/app/react/notifications/dev.mdx, packages/panda-preset/src/recipes/slots/notification.ts, packages/react/src/components/Notification.tsx, packages/react/src/context/notification-center.tsx, packages/react/src/context/notification-center/store.ts, packages/react/src/context/notification-center/types.ts, tests/panda-preset/recipes/slots/notification.test.ts, tests/react/context/notification-center.test.tsx
closes #847 
- Adds timeout to notifications
- Adds open/close transition to notifications
- Updates N.Center to properly useReducer for state
=> 847 feat add custom timeout for notificationscenter

docs/app/react/date-picker/components/static-preview.tsx, docs/app/react/date-picker/dev.mdx, docs/app/react/date-picker/guidelines.mdx, docs/app/react/date-picker/overview.mdx, packages/react/src/components/DatePicker.client.tsx, packages/react/src/context/notification-center.tsx, tests/react/components/datepicker.test.tsx, tests/react/context/notification-center.test.tsx
closes #849
Allows RangePickerInput to accept Array defaultValue
=> 849 feat allow defaultvalue for both range inputs in rangepicker

docs/app/react/dialog/components/modal-preview.tsx, docs/app/react/dialog/dev.mdx
closes #861 
Adds size preview example
=> docs: update modal-preview to include size

docs/app/components/PageTabs.tsx, packages/react/src/context/confirm-modal.tsx, packages/react/src/context/cta-modal.tsx, packages/react/src/context/prompt-modal.tsx, packages/react/src/index.ts, tests/react/context/cta-modal.test.tsx
closes #864 
Updates all modal templates to use dialog
=> 864 feat update template modals to use new dialog api

configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json, docs/app/react/side-nav.ts
=> 867 feat v0150

.github/workflows/checks.yml, .github/workflows/linting.yml, .github/workflows/publish-figma.yml, .github/workflows/publish-next.yml, .github/workflows/publish-stable.yml, docs/app/components/PageTabs.tsx, package.json, packages/react/package.json
=> 871 bug npm build error

docs/app/components/Admonition.tsx, docs/app/global-error.tsx, docs/app/react/modal/components/modal-preview.tsx, docs/app/react/modal/dev.mdx, docs/app/react/modal/guidelines.mdx, docs/app/react/modal/overview.mdx
closes #873 
- Adds deprecation to Modal page
- Adds missing panda configuration to global-error.tsx
=> 873 docs modal page crashes

docs/.eslintrc.json, docs/app/react/select/components/live-preview.tsx, docs/app/react/select/components/select-preview.tsx, docs/app/react/select/dev.mdx, packages/react/src/components/Select.server.tsx, packages/react/src/components/Select.tsx, packages/react/src/index.ts
closes #882 
Updates Select dev docs info
=> 882 docs update select dev docs

docs/app/react/button/components/live-playground.tsx, packages/panda-preset/src/recipes/button.ts, packages/react/src/components/Button.tsx, tests/panda-preset/recipes/button.test.ts
closes #881 
closes #875 
- Updates button recipe sizes
- Adds missing size prop to Button.tsx > recipe 🙈
=> fix(preset): update button sizes

packages/react/src/hooks/useRootColors.ts
=> chore: remove console log in useRootColors hook

configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json, docs/app/react/side-nav.ts, docs/app/react/toggle/doc.mdx
=> chore: up version v0.16

docs/app/react/tooltip/[slug]/dev.mdx
closes #991 
Adds missing Ark-UI dev link
=> docs: add missing ark link for tooltip/dev.mdx

configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json
=> 1013 feat v017

.github/workflows/publish-stable.yml, configs/src/bump-versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json, packages/styled-system/jsr.json, packages/styled-system/package.json
closes #1021 
Adjusts each job in publish to run bump versions
=> ci: update publish-stable

.github/workflows/publish-stable.yml, .gitignore, .npmrc, configs/src/versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json, packages/styled-system/jsr.json, packages/styled-system/package.json
closes #1024 
Reverts actions to use `pnpm publish` for workspace compatibility
=> 1024 bug 0171 unused aria type

packages/panda-preset/package.json, packages/panda-preset/src/recipes/slots/accordion.ts, packages/panda-preset/src/recipes/slots/avatar.ts, packages/panda-preset/src/recipes/slots/checkbox.ts, packages/panda-preset/src/recipes/slots/combobox.ts, packages/panda-preset/src/recipes/slots/datepicker.ts, packages/panda-preset/src/recipes/slots/dialog.ts, packages/panda-preset/src/recipes/slots/field.ts, packages/panda-preset/src/recipes/slots/fieldset.ts, packages/panda-preset/src/recipes/slots/menu.ts, packages/panda-preset/src/recipes/slots/radio.ts, packages/panda-preset/src/recipes/slots/ratingGroup.ts, packages/panda-preset/src/recipes/slots/select.ts, packages/panda-preset/src/recipes/slots/switch.ts, packages/panda-preset/src/recipes/slots/tabs.ts, packages/panda-preset/src/recipes/slots/toast.ts, packages/panda-preset/src/recipes/slots/tooltip.ts, pnpm-lock.yaml
closes #1041 
Replaces `@ark-ui/anatomy` with the preferred(?) `@ark-ui/react` for anatomy for panda-preset to avoid security errors
=> refactor: use ark-ui/react for anatomy

.github/workflows/publish-stable.yml, configs/package.json, configs/src/bump-versions.mjs, configs/src/versions.mjs, docs/app/data/categories.react.json, docs/app/preset/side-nav.json, package.json, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json
=> 1044 feat v018

docs/package.json, pnpm-lock.yaml
closes #1063 
Updates all the deps in the docs from dependabot
=> chore: up doc deps

docs/app/blog/cerberus-v018-release/page.mdx, docs/app/preset/customizing/doc.mdx, docs/app/preset/overview.mdx, docs/app/react/field-message/[slug]/dev.mdx, docs/app/react/forms/[slug]/dev.mdx, docs/app/react/portal/[slug]/dev.mdx, docs/app/react/switch/[slug]/dev.mdx, docs/app/react/toggle/[slug]/dev.mdx, docs/app/react/use-theme-context/overview/doc.mdx
closes #1068 
Adds correct import path for installation and blog guide for v0.18
=> docs: fix incorrect import path for preset

.github/workflows/checks.yml, eslint.config.mjs, package.json, packages/panda-preset/package.json, packages/solid/.gitignore, packages/solid/README.md, packages/solid/package.json, packages/solid/panda.config.ts, packages/solid/src/components/button/button-icon.tsx, packages/solid/src/components/button/button.tsx, packages/solid/src/components/button/context.ts, packages/solid/src/components/button/index.ts, packages/solid/src/components/button/parts.ts, packages/solid/src/components/spinner.tsx, packages/solid/src/index.ts, packages/solid/tsconfig.json, packages/solid/tsup.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml, solid-tests/.gitignore, solid-tests/components/button.test.tsx, solid-tests/global.d.ts, solid-tests/package.json, solid-tests/setup-test.ts, solid-tests/tsconfig.json, solid-tests/vitest.config.ts, tests/testing-library.ts
closes #1055 
- Adds solid & solid-tests workspaces
- Sets up build process for `/solid` package
- Sets up test environment for solid packages
- Adds CI jobs to run lint, build, and tests for solid packages
=> 1055 feat setup workspace

packages/solid/src/components/icon-button.tsx, packages/solid/src/index.ts, solid-tests/components/icon-button.test.tsx
closes #1074 
Adds IconButton to solid
=> feat(solid): add icon-button

packages/solid/src/components/tag.tsx, packages/solid/src/index.ts, solid-tests/components/tag.test.tsx
closes #1077 
Adds tag to solid
=> feat(solid): add tag component

.github/workflows/checks.yml, packages/solid/src/components/circular-progress.tsx, packages/solid/src/components/icon-button.tsx, packages/solid/src/components/tag.tsx, packages/solid/src/index.ts, solid-tests/components/circular-progress.test.tsx
closes #1081 
Adds CircularProgress to solid
=> feat(solid): add circular-progress

packages/solid/src/components/menu/index.ts, packages/solid/src/components/menu/parts.ts, packages/solid/src/components/menu/primitives.tsx, packages/solid/src/index.ts, solid-tests/components/menu.test.tsx
closes #1075 
Adds Menu to solid
=> feat(solid): add menu api

.github/workflows/publish-stable.yml, .gitignore, .npmrc, configs/src/versions.mjs, package.json, packages/solid/jsr.json
closes #1088 
Sets up the repo to publish solid packages
=> 1088 feat publish r1 solid

docs/app/react/progress-indicators/components/circular-preview.tsx, package.json, packages/panda-preset/package.json, packages/panda-preset/src/recipes/index.ts, packages/panda-preset/src/recipes/slots/circularProgress.ts, packages/react/package.json, packages/react/src/components/CircularProgress.tsx, packages/solid/README.md, packages/solid/package.json, packages/solid/src/components/circular-progress.tsx, pnpm-lock.yaml, tests/panda-preset/recipes/slots/circularProgress.test.ts, website/app.config.ts, website/package.json, website/src/components/shared/global-nav.tsx, website/src/routes/docs/index.tsx, website/tsconfig.json
closes #1095 
- Adds circularProgress recipe to prevent inline panda styling within components
- Update React, Solid components to use recipe
- Update development environment for solid
- Bump panda deps
=> 1095 bug make circularprogress slot recipe

docs/app/preset/customizing/doc.mdx, packages/panda-preset/src/config.ts, packages/panda-preset/src/theme/tokens.ts, website/panda.config.ts
closes #1089 
Adds font customization in `createCerberusPreset` helper
=> feat(preset): allow customizing fonts

packages/solid/src/components/button/button.tsx, packages/solid/src/components/spinner/index.tsx, website/src/routes/docs/index.tsx
closes #1105 
Updates the size prop for the Solid spinner to include a fallback size
=> fix(solid): fine tune spinner & button props

docs/app/preset/conditions/doc.mdx, packages/panda-preset/src/conditions.ts, packages/panda-preset/src/recipes/shared/button.base.ts, tests/panda-preset/conditions.test.ts, tests/panda-preset/recipes/button.test.ts, tests/panda-preset/recipes/iconButton.test.ts
closes #1120 
- Updates danger button recipes to use correct tokens for their unique use case
- Adds new `_notDisabled` condition
=> fix(preset): update button danger variants

configs/src/versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json, packages/solid/jsr.json, packages/solid/package.json
=> chore: bump version 0.18.2

docs/app/react/icon-button/[slug]/dev.mdx, docs/app/react/icon-button/[slug]/guidelines.mdx, docs/app/react/icon-button/[slug]/overview.mdx, docs/app/react/icon-button/components/icon-button-preview.tsx, docs/package.json, pnpm-lock.yaml
closes #1143 
Updates docs to reflect current customization strategy
=> docs: update IconButton.dev page

packages/solid/src/components/avatar/avatar.tsx, packages/solid/src/components/avatar/primitives.tsx, packages/solid/src/components/button/button.tsx, packages/solid/src/components/icon-button/icon-button.tsx, packages/solid/src/components/menu/primitives.tsx, packages/solid/src/components/rating/primitives.tsx, packages/solid/src/components/rating/rating.tsx, packages/solid/src/components/tag/tag.tsx, packages/solid/src/components/types.ts, website/src/components/shared/global-nav.tsx, website/src/routes/docs/index.tsx
closes #1176 
Updates all solid components to support customizing via the `css` prop to ensure styles merge effectively
=> 1176 feat support css prop

configs/src/versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json, packages/solid/jsr.json, packages/solid/package.json
=> chore: bump version 0.18.3

docs/package.json, pnpm-lock.yaml
closes #1201 
Updates all doc deps from weekly dependabot check
=> chore: bump docs deps

packages/panda-preset/src/theme/semantic-tokens/danger.ts, packages/panda-preset/src/theme/semantic-tokens/info.ts, packages/panda-preset/src/theme/semantic-tokens/page.ts, packages/panda-preset/src/theme/semantic-tokens/success.ts, packages/panda-preset/src/theme/semantic-tokens/types.ts, packages/panda-preset/src/theme/semantic-tokens/warning.ts, packages/panda-preset/src/themes/acheron/semantic-tokens/danger.ts, packages/panda-preset/src/themes/acheron/semantic-tokens/info.ts, packages/panda-preset/src/themes/acheron/semantic-tokens/page.ts, packages/panda-preset/src/themes/acheron/semantic-tokens/success.ts, packages/panda-preset/src/themes/acheron/semantic-tokens/warning.ts, tests/panda-preset/config.test.ts, tests/panda-preset/themes/semantic-tokens/acheron-page.test.ts, tests/panda-preset/themes/semantic-tokens/base-page.test.ts
Missing some new tokens declared in the sync
Adds em!
=> Dependabot/npm and yarn/docs/types/react dom 19.1.5

docs/app/components/page-tabs/four-tab-layout.tsx, docs/app/components/page-tabs/two-tab-layout.tsx, docs/app/preset/animation/components/animate-in-preview.tsx, docs/app/preset/animation/doc.mdx, packages/panda-preset/src/patterns.ts, tests/panda-preset/patterns.test.ts
closes #1263 
closes #1218 
Updates `animateIn` to use `_motionSafe` condition and not reduce
=> fix(preset): update animateIn to use motionSafe condition

docs/app/react/text/[slug]/dev.mdx, docs/app/react/text/components/show-preview.tsx, packages/panda-preset/src/patterns.ts, packages/react/src/components/Text.tsx, tests/panda-preset/patterns.test.ts
closes #1266 
Adds missing color prop to all Text patterns
=> fix(preset): add color prop to text patterns

packages/panda-preset/src/recipes/slots/field.ts, packages/panda-preset/src/recipes/slots/switch.ts, tests/panda-preset/recipes/slots/field.test.ts, tests/panda-preset/recipes/slots/switch.test.ts
closes #1268 
- Updates tokens in switch recipe
- Updates cursor states for switch
=> chore(preset): fine tune switch styles

docs/app/react/confirm-modal/components/confirm-modal-features.tsx, docs/app/react/textarea/[slug]/dev.mdx, docs/app/react/textarea/components/static-preview.tsx, docs/panda.config.ts, packages/panda-preset/src/recipes/slots/dialog.ts, packages/panda-preset/src/recipes/slots/field.ts, packages/react/src/components/cta-dialog/provider.tsx, packages/react/src/components/dialog/dialog.tsx, packages/react/src/components/dialog/primitives.tsx, packages/react/src/components/field/field.tsx, packages/react/src/components/field/helper-text.tsx, packages/react/src/components/field/primitives.tsx, packages/react/src/context/confirm-modal.tsx, packages/react/src/context/prompt-modal.tsx, packages/react/src/types.ts, tests/panda-preset/recipes/slots/dialog.test.ts, tests/panda-preset/recipes/slots/field.test.ts
closes #1264 
- Updates modal spacing for all templated modals
- Adds `WithCss` export
- Adds `auto` size for `dialog` recipe
=> 1264 bug template modal spacing is off

configs/src/versions.mjs, docs/app/components/Nav.tsx, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json
=> 1302 feat cut v0184 release

docs/app/blog/page.tsx, docs/app/docs/components/[slug]/components/theme/static.tsx, docs/app/docs/components/[slug]/content/items/utilities.ts, docs/app/docs/components/[slug]/content/show.mdx, docs/app/docs/components/[slug]/content/theme.mdx, docs/app/docs/styling/[slug]/content/theme-mode.mdx, packages/react/src/components/theme/index.ts, packages/react/src/components/theme/theme.tsx, packages/react/src/index.ts, tests/react/components/theme.test.tsx
closes #1351 
- Adds new Theme component
- Adds theme docs
=> 1351 feat add theme component for easy nested management

configs/src/versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json
=> chore: bump versions

configs/src/versions.mjs, docs/app/docs/styling/[slug]/content/animation-styles.mdx, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json
=> chore: bump version 0.20.0

docs/app/blog/[slug]/content/items.ts, docs/app/blog/[slug]/content/v21-release.mdx
=> docs: create v0.21 blog

configs/src/versions.mjs, packages/panda-preset/jsr.json, packages/panda-preset/package.json, packages/react/jsr.json, packages/react/package.json, packages/react/vite.config.mts
closes #1548 
Updates vite config to not make server APIs client
=> 1548 bug hotfix 0212 fine tune react build output

packages/panda-preset/src/recipes/slots/datepicker.ts, tests/panda-preset/recipes/slots/datePicker.test.ts
closes #1567 
Adds additional 1rem to rangepicker control width
=> fix(preset): update range picker width to fit placeholder text

docs/app/docs/components/[slug]/components/cta-modal/cta-modal-features.tsx, docs/app/docs/components/[slug]/components/cta-modal/static.tsx, docs/app/docs/components/[slug]/content/cta-modal.mdx, packages/react/src/components/cta-dialog/context.tsx, packages/react/src/components/cta-dialog/provider.tsx
closes #1605 
- Updates CTA options to support `content`
=> feat(react): update cta-modal to support custom content
